version: "3.1"

services:
    dev:
      build: ..
      image: iu9-networks:latest
      privileged: true
      network_mode: host
      volumes:
        - .:/service:rw
        - gopath:/go
        - build_cache:/root/.cache/go-build
        - ci_cache:/root/.cache/golangci-lint
        - /var/run/docker.sock:/var/run/docker.sock
      working_dir: /service

volumes:
  gopath:
  build_cache:
  ci_cache:
