version: "3.1"

services:
    dev:
      build:
        context: ./../
      privileged: true
      network_mode: host
      volumes:
        - .:/service:rw
        - /go/pkg/mod
        - /root/.cache/go-build
        - /root/.cache/golangci-lint
      working_dir: /service
      entrypoint:
        - bash
