version: "3.1"

services:
    dev:
      build: ..
      image: iu9-networks:latest
      privileged: true
      network_mode: host
      volumes:
        - .:/service:rw
        - .cache/go/mod:/go/mod
        - .cache/go-build:/root/.cache/go-build
        - .cache/ci-cache:/root/.cache/golangci-lint
        - /var/run/docker.sock:/var/run/docker.sock
      working_dir: /service

